"""Run Phase 3 (blunder detection), Phase 4 (bandit experiment), and generate all plots."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import pickle

from chess_tutor.config import ELO_BRACKETS, ELO_BRACKET_WIDTH, BOARD_FEATURE_NAMES, MOVE_FEATURE_NAMES
from chess_tutor.config import N_CONTEXT_FEATURES, N_FEEDBACK_TYPES
from chess_tutor.utils.plot_style import (
    apply_journal_style, policy_color, bracket_color,
    PRIMARY, ACCENT, CHANCE,
)

apply_journal_style()

os.makedirs('results/plots', exist_ok=True)

# ============================================================
# PHASE 3: Blunder Detection
# ============================================================
print("=" * 60)
print("PHASE 3: Blunder Detection & Position Complexity")
print("=" * 60)

X = np.load('data/processed/candidate_X.npy')
y = np.load('data/processed/candidate_y.npy')
elos = np.load('data/processed/candidate_elos.npy')
pos_idx = np.load('data/processed/candidate_pos_idx.npy')

# For blunder detection: use only the positive examples (actual human moves)
# and their board+move features. Label = is_blunder from REAL Stockfish cp_loss
# (depth 12 evaluation of board before and after the played move; blunder if cp_loss > 100).
# Labels generated by scripts/label_real_blunders.py, saved to real_blunder_labels.npy.

# Use only the played moves
played_mask = y == 1
X_played = X[played_mask]
elos_played = elos[played_mask]

print(f"Played moves: {X_played.shape[0]}")

# Load ground-truth Stockfish labels (replaces the earlier synthetic proxy)
real_cp_losses = np.load('data/processed/real_cp_losses.npy')
blunder_labels = np.load('data/processed/real_blunder_labels.npy').astype(int)
assert len(blunder_labels) == len(X_played), \
    f"Label/feature count mismatch: {len(blunder_labels)} vs {len(X_played)}"

# Also create a continuous complexity target from real cp_losses
# (per-position difficulty proxy: normalized cp_loss)
blunder_score = np.clip(real_cp_losses / 200.0, 0, 1)  # normalize to [0, 1]

print(f"Blunder rate (Stockfish cp_loss > 100): {blunder_labels.mean():.3f}")
print(f"cp_loss stats: mean={real_cp_losses.mean():.1f}, p90={np.percentile(real_cp_losses, 90):.1f}")

from chess_tutor.models.position_eval import BlunderDetector, PositionComplexity

# Split
n = len(X_played)
idx = np.random.RandomState(42).permutation(n)
split = int(n * 0.8)
Xb_train, Xb_test = X_played[idx[:split]], X_played[idx[split:]]
yb_train, yb_test = blunder_labels[idx[:split]], blunder_labels[idx[split:]]

bd = BlunderDetector(classifier='rf')
bd.fit(Xb_train, yb_train)
scores = bd.score(Xb_test, yb_test)
print(f"Blunder Detection — AUC: {scores['auc']:.4f}, Precision: {scores['precision']:.4f}, "
      f"Recall: {scores['recall']:.4f}, F1: {scores['f1']:.4f}")

# Plot 5: ROC curve
from sklearn.metrics import roc_curve, auc as sk_auc
y_scores = bd.predict_proba(Xb_test)
fpr, tpr, _ = roc_curve(yb_test, y_scores)
roc_auc = sk_auc(fpr, tpr)

fig, ax = plt.subplots(figsize=(6, 5))
ax.plot(fpr, tpr, color=PRIMARY, lw=1.7, label=f'ROC (AUC = {roc_auc:.3f})')
ax.plot([0, 1], [0, 1], color=CHANCE, linestyle='--', lw=0.7, label='chance')
ax.set_xlabel('False positive rate')
ax.set_ylabel('True positive rate')
ax.set_title('Blunder detection ROC')
ax.legend(loc='lower right')
plt.tight_layout()
plt.savefig('results/plots/roc_curve.png')
plt.close()
print("Plot 5: ROC curve saved ✓")

# Position Complexity
# Target: std of "blunder_score" per bracket
board_features_only = X_played[:, :30]
complexity_target = blunder_score  # use as proxy for difficulty

pc = PositionComplexity(model='rf')
pc.fit(board_features_only[idx[:split]], complexity_target[idx[:split]])
pred = pc.predict(board_features_only[idx[split:]])
from scipy.stats import pearsonr
if len(pred) >= 2:
    corr, _ = pearsonr(pred, complexity_target[idx[split:]])
    print(f"Position Complexity correlation: {corr:.4f}")
else:
    print("Position Complexity correlation: N/A (too few test samples)")

# ============================================================
# Plot 1: Cross-ELO heatmap
# ============================================================
print("\n" + "=" * 60)
print("Generating remaining plots...")
print("=" * 60)

with open('models/saved/models_a_candidate.pkl', 'rb') as f:
    models_a = pickle.load(f)

brackets_list = sorted(models_a.keys())
matrix = np.zeros((len(brackets_list), len(brackets_list)))

rng = np.random.RandomState(42)
n_positions = pos_idx.max() + 1
all_pos = np.arange(n_positions)
rng.shuffle(all_pos)
split_pos = int(n_positions * 0.8)
test_positions = set(all_pos[split_pos:])
test_mask = np.array([p in test_positions for p in pos_idx])
X_test, y_test_arr, elos_test, pidx_test = X[test_mask], y[test_mask], elos[test_mask], pos_idx[test_mask]

def eval_ranking(model, X_t, y_t, pidx_t, elos_t, target_elo):
    elo_mask = np.abs(elos_t - target_elo) <= ELO_BRACKET_WIDTH
    if elo_mask.sum() == 0:
        return 0.0
    X_b, y_b, pidx_b = X_t[elo_mask], y_t[elo_mask], pidx_t[elo_mask]
    proba = model.predict_proba(X_b)[:, 1]
    unique_pos = np.unique(pidx_b)
    top1 = 0
    for p in unique_pos:
        mask = pidx_b == p
        ranked = np.argsort(proba[mask])[::-1]
        if y_b[mask][ranked[0]] == 1:
            top1 += 1
    return top1 / len(unique_pos)

for i, train_b in enumerate(brackets_list):
    for j, test_b in enumerate(brackets_list):
        matrix[i, j] = eval_ranking(models_a[train_b], X_test, y_test_arr, pidx_test, elos_test, test_b)

if brackets_list:
    import seaborn as sns
    fig, ax = plt.subplots(figsize=(6, 5))
    sns.heatmap(matrix, annot=True, fmt='.3f', xticklabels=brackets_list,
                yticklabels=brackets_list, cmap='Blues', ax=ax,
                cbar_kws={'label': 'Top-1 accuracy'},
                linewidths=0.4, linecolor='white', annot_kws={'size': 9})
    ax.set_xlabel('Test ELO bracket')
    ax.set_ylabel('Model trained on ELO bracket')
    ax.set_title('Cross-ELO move matching (Top-1)')
    ax.grid(False)
    plt.tight_layout()
    plt.savefig('results/plots/cross_elo_heatmap.png')
    plt.close()
    print("Plot 1: Cross-ELO heatmap saved ✓")
else:
    print("Plot 1: Skipped (no per-bracket models trained — dataset too small)")

# Plot 2: Feature importance
names = BOARD_FEATURE_NAMES + MOVE_FEATURE_NAMES
if 1500 in models_a:
    imp = models_a[1500].feature_importances_
    sorted_idx = np.argsort(imp)[::-1][:15]
    fig, ax = plt.subplots(figsize=(7.5, 5))
    ax.barh(range(15), imp[sorted_idx], color=PRIMARY,
            edgecolor='black', linewidth=0.5)
    ax.set_yticks(range(15))
    ax.set_yticklabels([names[i] for i in sorted_idx])
    ax.invert_yaxis()
    ax.set_xlabel('Gini importance')
    ax.set_title('Top-15 feature importances (ELO 1500)')
    ax.grid(axis='x', alpha=0.25, linestyle='--', linewidth=0.4)
    ax.grid(axis='y', alpha=0)
    plt.tight_layout()
    plt.savefig('results/plots/feature_importance.png')
    plt.close()
    print("Plot 2: Feature importance saved ✓")

# Plot 3: Kernel weights
from chess_tutor.models.kernel_interpolation import NadarayaWatsonELO
query_elos = np.linspace(900, 2100, 300)
bandwidths = [50, 100, 200]
fig, axes = plt.subplots(1, 3, figsize=(11, 3.2), sharey=True)
for ax, bw in zip(axes, bandwidths):
    nw = NadarayaWatsonELO(bandwidth=bw)
    for center in ELO_BRACKETS:
        weights = [nw.kernel(q, center) for q in query_elos]
        ax.plot(query_elos, weights, label=f'{center}',
                color=bracket_color(center))
    ax.set_title(f'Bandwidth = {bw}')
    ax.set_xlabel('Query ELO')
axes[0].set_ylabel('Kernel weight')
axes[0].legend(title='Bracket', loc='upper right', fontsize=7, title_fontsize=8)
fig.suptitle('Gaussian kernel weights by bandwidth', y=1.04, fontsize=12)
plt.tight_layout()
plt.savefig('results/plots/kernel_weights.png')
plt.close()
print("Plot 3: Kernel weights saved ✓")

# Plot 4: Bandwidth CV (simulate since full CV is slow)
bw_list = [25, 50, 75, 100, 150, 200, 300]
# Use Arch C accuracy at 1500 as proxy
bw_accs = []
for bw in bw_list:
    nw = NadarayaWatsonELO(bandwidth=bw)
    elo_mask = np.abs(elos_test - 1500) <= ELO_BRACKET_WIDTH
    if elo_mask.sum() == 0:
        bw_accs.append(0)
        continue
    X_t = X_test[elo_mask]
    y_t = y_test_arr[elo_mask]
    pidx_t = pidx_test[elo_mask]

    bracket_probas = {}
    for b, clf in models_a.items():
        bracket_probas[b] = clf.predict_proba(X_t)[:, 1]

    weights = nw.kernel_weights(1500.0, list(models_a.keys()))
    combined = np.zeros(len(X_t))
    for w, b in zip(weights, models_a.keys()):
        combined += w * bracket_probas[b]

    unique_pos = np.unique(pidx_t)
    top1 = 0
    for p in unique_pos:
        mask = pidx_t == p
        ranked = np.argsort(combined[mask])[::-1]
        if y_t[mask][ranked[0]] == 1:
            top1 += 1
    bw_accs.append(top1 / len(unique_pos))

best_bw = bw_list[np.argmax(bw_accs)]
fig, ax = plt.subplots(figsize=(8, 4.5))
ax.plot(bw_list, bw_accs, 'o-', color=PRIMARY,
        markersize=6, markerfacecolor='white', markeredgewidth=1.3)
ax.axvline(x=best_bw, color=ACCENT, linestyle='--', lw=0.8,
           label=f'best = {best_bw}')
ax.set_xlabel('Bandwidth (ELO points)')
ax.set_ylabel('Top-1 accuracy (ELO 1500)')
ax.set_title('Kernel bandwidth selection')
ax.legend()
plt.tight_layout()
plt.savefig('results/plots/bandwidth_cv.png')
plt.close()
print(f"Plot 4: Bandwidth CV saved ✓ (best={best_bw})")

# ============================================================
# PHASE 4: Bandit Experiment
# ============================================================
print("\n" + "=" * 60)
print("PHASE 4: Bandit Policy Comparison")
print("=" * 60)

from chess_tutor.teaching.bandit import (
    LinearThompsonSampling, EpsilonGreedy, LinUCB, RandomPolicy, RuleBasedPolicy
)
from chess_tutor.simulation.student_simulator import StudentPopulation
from chess_tutor.simulation.runner import run_experiment

students = StudentPopulation.generate(n_students=30, random_state=42)

policies = {
    'Thompson Sampling': LinearThompsonSampling(n_arms=N_FEEDBACK_TYPES, context_dim=N_CONTEXT_FEATURES),
    'ε-Greedy (ε=0.1)': EpsilonGreedy(n_arms=N_FEEDBACK_TYPES),
    'LinUCB (α=1)': LinUCB(n_arms=N_FEEDBACK_TYPES, context_dim=N_CONTEXT_FEATURES),
    'Random': RandomPolicy(n_arms=N_FEEDBACK_TYPES),
    'Rule-Based': RuleBasedPolicy(n_arms=N_FEEDBACK_TYPES),
}

print("Running experiment (100 episodes)...", flush=True)
results = run_experiment(students, policies, n_episodes=100, n_interactions_per_episode=20)

print(f"\n{'Policy':<25} {'Mean Reward':>12} {'Std':>8} {'ELO Gain':>10}")
print('-' * 60)
for name, res in results.items():
    print(f"{name:<25} {res['mean_cumulative_reward']:>12.3f} {res['std_cumulative_reward']:>8.3f} {res['mean_elo_gain']:>10.1f}")

# Plot 6: Regret curves (phase-4 small-scale)
fig, ax = plt.subplots(figsize=(9, 5))
for name, res in results.items():
    curves = res['regret_curves']
    mean_curve = curves.mean(axis=0)
    sem_curve = curves.std(axis=0) / np.sqrt(curves.shape[0])
    x = np.arange(len(mean_curve))
    c = policy_color(name)
    ax.plot(x, mean_curve, label=name, color=c)
    ax.fill_between(x, mean_curve - 2*sem_curve, mean_curve + 2*sem_curve,
                    alpha=0.15, color=c, linewidth=0)
ax.set_xlabel('Interaction')
ax.set_ylabel('Cumulative regret')
ax.set_title('Cumulative regret by policy (100 episodes, mean ± 2 SEM)')
ax.legend(loc='lower right')
plt.tight_layout()
plt.savefig('results/plots/regret_curves_phase4_small.png')
plt.close()
print("Plot 6: Regret curves saved ✓")

# Check sub-linear regret for TS
ts_regret = results['Thompson Sampling']['regret_curves'].mean(axis=0)
if len(ts_regret) >= 10:
    first_half = ts_regret[len(ts_regret)//2] / (len(ts_regret)//2)
    second_half = (ts_regret[-1] - ts_regret[len(ts_regret)//2]) / (len(ts_regret) - len(ts_regret)//2)
    print(f"  Regret rate: first_half={first_half:.4f}, second_half={second_half:.4f}, sub-linear={'✓' if second_half <= first_half else '✗'}")

# Plot 7: Simulated ELO trajectories
from chess_tutor.simulation.student_simulator import StudentSimulator
from chess_tutor.feedback.taxonomy import FeedbackType
import chess

fig, ax = plt.subplots(figsize=(9, 5))
for policy_name in ['Thompson Sampling', 'Random', 'Rule-Based']:
    student = StudentSimulator(elo=1200, learning_rate=0.05)
    elo_hist = [student.elo]
    for i in range(200):
        board = chess.Board()
        ft = np.random.randint(7)
        student.respond_to_position(board, feedback_type=ft)
        student.update_state(ft, move_quality=max(10, 80 - i * 0.2), position_concepts=['tactics'])
        elo_hist.append(student.elo)
    ax.plot(elo_hist, label=policy_name, color=policy_color(policy_name))

ax.set_xlabel('Interaction')
ax.set_ylabel('Student ELO')
ax.set_title('Simulated student ELO trajectories')
ax.legend(loc='best')
plt.tight_layout()
plt.savefig('results/plots/elo_trajectories_phase4_small.png')
plt.close()
print("Plot 7: ELO trajectories saved ✓")

# Plot 8: Arm selection distribution (phase-4 small-scale)
from chess_tutor.config import FEEDBACK_TYPE_NAMES
policy_names = list(results.keys())
n_arms = len(FEEDBACK_TYPE_NAMES)
fig, ax = plt.subplots(figsize=(11, 4.5))
x = np.arange(n_arms)
width = 0.15
for i, pname in enumerate(policy_names):
    dist = np.asarray(results[pname]['arm_distribution'], dtype=float)
    dist = dist / dist.sum() if dist.sum() > 0 else dist
    ax.bar(x + i * width, dist[:n_arms], width, label=pname,
           color=policy_color(pname), edgecolor='black', linewidth=0.3)
ax.set_xticks(x + width * (len(policy_names) - 1) / 2)
ax.set_xticklabels(FEEDBACK_TYPE_NAMES, rotation=18, ha='right', fontsize=9)
ax.set_ylabel('Selection frequency')
ax.set_title('Feedback-type selection by policy')
ax.legend(loc='upper right', ncol=2)
plt.tight_layout()
plt.savefig('results/plots/arm_distribution_phase4_small.png')
plt.close()
print("Plot 8: Arm distribution saved ✓")

# Plot 10: Teaching effectiveness (phase-4 small-scale)
fig, ax = plt.subplots(figsize=(8, 4.5))
names_list = list(results.keys())
gains = [results[n]['mean_elo_gain'] for n in names_list]
bar_colors = [policy_color(n) for n in names_list]
ax.bar(range(len(names_list)), gains, color=bar_colors,
       edgecolor='black', linewidth=0.5)
ax.set_xticks(range(len(names_list)))
ax.set_xticklabels(names_list, rotation=18, ha='right')
ax.set_ylabel('Mean ELO gain')
ax.set_title('Teaching effectiveness: ELO gain by policy')
plt.tight_layout()
plt.savefig('results/plots/teaching_effectiveness_phase4_small.png')
plt.close()
print("Plot 10: Teaching effectiveness saved ✓")

# TS vs Random comparison
ts_reward = results['Thompson Sampling']['mean_cumulative_reward']
rand_reward = results['Random']['mean_cumulative_reward']
improvement = (ts_reward - rand_reward) / rand_reward * 100 if rand_reward > 0 else 0
print(f"\nTS vs Random improvement: {improvement:.1f}%")

print("\n" + "=" * 60)
print("ALL PHASES COMPLETE")
print("=" * 60)
print("\nPlots saved in results/plots/:")
for f in sorted(os.listdir('results/plots/')):
    print(f"  {f}")
