"""Episode runner and experiment harness for teaching policy evaluation."""

import copy
import os
import random as _py_random
import chess
import numpy as np
from typing import Protocol

from ..feedback.taxonomy import FeedbackType, FEEDBACK_CONCEPT_MAP
from ..teaching.reward import compute_reward
from ..config import PIECE_VALUES


# ---------------------------------------------------------------------------
# Empirical cp_loss distribution loaded from real Stockfish labels.
# Populated lazily the first time a cp_loss sample is needed.
# ---------------------------------------------------------------------------
_REAL_CP_BY_ELO: dict[int, np.ndarray] | None = None


def _load_real_cp_loss_distribution():
    """Load the 35,140 real Stockfish-labeled cp_losses (depth 12) and
    bucket them by ELO bracket. Populates the module-level cache.

    Source: ``data/processed/real_cp_losses.npy`` generated by
    ``scripts/label_real_blunders.py``.
    """
    global _REAL_CP_BY_ELO
    if _REAL_CP_BY_ELO is not None:
        return _REAL_CP_BY_ELO

    cp_path = "data/processed/real_cp_losses.npy"
    elos_path = "data/processed/candidate_elos.npy"
    y_path = "data/processed/candidate_y.npy"

    if not (os.path.exists(cp_path) and os.path.exists(elos_path)
            and os.path.exists(y_path)):
        # Fallback: use heuristic distribution (exponential with mean 50,
        # matching the empirical mean from our real labels)
        _REAL_CP_BY_ELO = {}
        return _REAL_CP_BY_ELO

    cp = np.load(cp_path)
    elos = np.load(elos_path)
    y = np.load(y_path)
    # cp is indexed by (played-move) rows only; filter elos correspondingly
    played_elos = elos[y == 1]
    assert len(played_elos) == len(cp), \
        f"Shape mismatch: {len(played_elos)} elos vs {len(cp)} cp_losses"

    buckets: dict[int, list] = {1100: [], 1300: [], 1500: [], 1700: [], 1900: []}
    for e, c in zip(played_elos, cp):
        # Nearest bracket
        nearest = min(buckets.keys(), key=lambda b: abs(b - e))
        buckets[nearest].append(float(c))

    _REAL_CP_BY_ELO = {b: np.array(v, dtype=np.float32)
                       for b, v in buckets.items() if len(v) > 0}
    return _REAL_CP_BY_ELO


_SORTED_CP_BY_ELO: dict[int, np.ndarray] | None = None


def _get_sorted_cp_by_elo() -> dict[int, np.ndarray]:
    """Lazy cache of per-bracket cp_loss arrays, sorted ascending."""
    global _SORTED_CP_BY_ELO
    if _SORTED_CP_BY_ELO is None:
        buckets = _load_real_cp_loss_distribution()
        _SORTED_CP_BY_ELO = {b: np.sort(v) for b, v in buckets.items()}
    return _SORTED_CP_BY_ELO


def _relevant_concepts_for_board(board) -> list[str]:
    """Return the concepts most relevant to the given board position.

    Used by ``_sample_real_cp_loss`` to decide which part of the
    student's weakness profile to draw from — e.g., an endgame board
    weights the student's endgame mastery more than their opening
    mastery. This is an explicit modelling assumption in the simulator,
    not in the reward function.
    """
    if board is None:
        return ["tactics", "strategy", "endgame", "opening", "calculation"]

    from ..data.extract_features import detect_game_phase
    concepts = ["calculation"]  # always partly relevant

    phase = detect_game_phase(board)
    if phase == "opening":
        concepts.append("opening")
        concepts.append("strategy")
    elif phase == "endgame":
        concepts.append("endgame")
    else:
        concepts.append("strategy")

    # Tactics is relevant whenever the position has concrete threats
    has_tactics = sum(1 for m in board.legal_moves if board.is_capture(m)) >= 2
    if has_tactics or board.is_check():
        concepts.append("tactics")

    return concepts


def _move_quality_shift(board: chess.Board, move: chess.Move) -> float:
    """Percentile shift in [-0.25, +0.25] based on the *actual* move played.

    Negative shift → sample from a lower (better) percentile of the
    bracket's empirical cp_loss distribution; positive shift → higher
    (worse) percentile. This is the signal that couples the move the
    student actually plays to the cp_loss used for reward, closing the
    previous gap where ``run_episode`` sampled cp_loss independently of
    the move.

    Heuristic (no Stockfish dependency):
      * Capture of an undefended piece, or safe capture  →  slight bonus.
      * Capture that loses material (attacked, undefended, attacker
        worth more)  →  penalty scaled by net loss.
      * Non-capture move that drops a non-king piece on a square that
        is attacked but not defended  →  penalty scaled by piece value.
      * Checks get a small bonus (forcing moves tend to lose less).
    """
    piece = board.piece_at(move.from_square)
    if piece is None:
        return 0.0

    to_sq = move.to_square
    after = board.copy()
    after.push(move)
    attackers_after = after.attackers(not board.turn, to_sq)
    defenders_after = after.attackers(board.turn, to_sq)
    our_val = float(PIECE_VALUES.get(piece.piece_type, 0))

    shift = 0.0
    if board.is_capture(move):
        captured = board.piece_at(to_sq)
        cap_val = float(PIECE_VALUES.get(captured.piece_type, 100)) if captured else 100.0
        if defenders_after or not attackers_after:
            shift -= 0.15  # safe capture — clearly a strong move
        else:
            net = cap_val - our_val  # negative = losing trade
            if net < 0:
                # Losing trade: scale with material lost so a Q-for-P trade
                # actually pushes the percentile toward the worst cp_losses
                # in the bucket.  Old divisor (400) only produced a 0.25
                # cap even when a queen was thrown away; 200 is closer to
                # realistic cp_loss magnitude.
                shift += min(0.55, -net / 200.0)
            else:
                shift -= 0.05
    else:
        if attackers_after and not defenders_after and piece.piece_type != chess.KING:
            # Dropping a piece to an attacked undefended square.  Use the
            # same 200-denominator so a bishop (330cp) or queen (900cp)
            # drop moves the percentile substantially, not a flat 0.25.
            shift += min(0.55, our_val / 200.0)

    if board.gives_check(move):
        shift -= 0.05

    return float(np.clip(shift, -0.3, 0.55))


def _sample_real_cp_loss(student, board=None, move: chess.Move | None = None,
                         rng: np.random.RandomState | None = None) -> float:
    """Sample a cp_loss for the student's next move, **conditioned on both
    the student's skill level and the concepts relevant to the position**.

    Draws a base value from the empirical Stockfish-labeled distribution
    (35,140 real Lichess moves) at the student's ELO bracket, then
    selects the *percentile* within that distribution based on the
    student's mastery of the concepts active in this position:

    * High mastery on the relevant concepts  →  low percentile  →
      the student plays like the best 1500-rated players in this
      kind of position (low cp_loss).
    * Low mastery on the relevant concepts   →  high percentile  →
      the student plays like the worst 1500-rated players in this
      kind of position (high cp_loss).

    The **relevant concepts are position-specific**: a tactical
    middlegame weights tactics mastery; an endgame weights endgame
    mastery; an opening weights opening + strategy mastery. This is
    an explicit modelling assumption in the simulator (see
    ``_relevant_concepts_for_board``).

    Because the student's concept-specific mastery is updated by the
    bandit's arm choices (via ``StudentSimulator.update_state``), the
    arm choice **changes the next turn's cp_loss through the
    simulator** — not through any hand-crafted alignment in the
    reward function. The reward function itself is purely
    ``max(0, 1 − cp_loss/200)`` with no arm dependence.

    Args:
        student: either a StudentSimulator or a StudentState.
        board: optional chess.Board — used to determine which concepts
            are relevant at this position. If ``None``, falls back to
            mean mastery across all concepts.
        move: optional chess.Move — the move the student actually
            played. When provided, its quality (capture safety, piece
            drops, checks) shifts the percentile drawn from the
            empirical distribution so the cp_loss reflects the move in
            hand rather than a move-independent sample.
        rng: optional numpy RandomState for reproducibility.

    Returns:
        A cp_loss value in centipawns.
    """
    # Unpack student argument
    if hasattr(student, "elo") and hasattr(student, "weakness_profile"):
        elo = student.elo
        profile = student.weakness_profile
    elif hasattr(student, "state"):
        elo = student.state.elo
        profile = student.state.weakness_profile
    else:
        elo = int(student)
        profile = None

    r = rng or np.random

    sorted_buckets = _get_sorted_cp_by_elo()
    if not sorted_buckets:
        # Fallback: exponential with mean 50 (matches empirical mean)
        return float(r.exponential(50.0))

    # Find nearest ELO bracket
    nearest = min(sorted_buckets.keys(), key=lambda b: abs(b - elo))
    sorted_samples = sorted_buckets[nearest]
    n = len(sorted_samples)

    # Determine which percentile of that bucket to draw from, based on
    # the student's mastery of the concepts relevant to this position.
    if profile:
        concepts = _relevant_concepts_for_board(board)
        concept_masteries = [profile.get(c, 0.5) for c in concepts]
        relevant_mastery = float(np.mean(concept_masteries))
        # Mastery 0 -> percentile 1 (worst moves); mastery 1 -> percentile 0 (best moves).
        target_percentile = 1.0 - relevant_mastery
    else:
        target_percentile = 0.5

    # Couple cp_loss to the actual move via a quality-based percentile shift.
    if move is not None and board is not None:
        target_percentile += _move_quality_shift(board, move)

    noise = r.normal(0.0, 0.08)
    percentile = float(np.clip(target_percentile + noise, 0.10, 0.90))
    idx = int(percentile * (n - 1))
    return float(sorted_samples[idx])


class Policy(Protocol):
    """Interface that all bandit policies must implement."""
    def select_arm(self, context: np.ndarray) -> int: ...
    def update(self, arm: int, context: np.ndarray, reward: float) -> None: ...


def run_episode(
    student,
    policy,
    feedback_generator,
    context_builder_fn,
    reward_fn,
    positions: list[chess.Board],
    n_interactions: int = 20,
    seed: int | None = None,
) -> dict:
    """Run a single teaching episode.

    Args:
        seed: if provided, re-seeds both ``numpy`` and ``random`` global
            RNGs at the start of the episode so the trajectory is
            deterministic. Required for reproducible experiments —
            commentary/feedback generators use the ``random`` module and
            bandit policies and samplers use ``numpy.random``.

    Returns:
        dict with rewards, cumulative_reward, arms_selected,
        student_elo_trajectory, cp_loss_trajectory
    """
    if seed is not None:
        np.random.seed(seed)
        _py_random.seed(seed)

    rewards = []
    arms_selected = []
    elo_trajectory = [student.elo]
    cp_loss_trajectory = []

    for t in range(min(n_interactions, len(positions))):
        board = positions[t % len(positions)].copy()

        if board.is_game_over():
            continue

        # Build context
        from ..data.extract_features import extract_board_features
        board_features = extract_board_features(board)

        hanging = int(board_features[29])
        king_safety = float(board_features[14])
        blunder_prob = min(0.1 + 0.25 * hanging + 0.1 * (king_safety < 2), 1.0)
        complexity = min(board.legal_moves.count() / 40.0, 1.0)

        context = context_builder_fn(
            board=board,
            student_state=student.state,
            blunder_prob=blunder_prob,
            complexity=complexity,
            board_features=board_features,
        )

        # Select feedback type
        arm = policy.select_arm(context)
        arms_selected.append(arm)

        # Generate feedback
        feedback_type = FeedbackType(arm)
        feedback_text = feedback_generator.generate(
            board, student.elo, feedback_type
        )

        # Student responds with feedback. If the feedback is relevant to
        # a concept the student is weak in, the student may upgrade to a
        # better move (ZPD-style learning inside the simulator).
        actual_move = student.respond_to_position(
            board, feedback_type=arm, feedback_text=feedback_text
        )
        # Sample cp_loss conditioned on (a) the student's current mastery
        # of the concepts relevant to this specific board, and (b) the
        # quality of the move the student actually played. Two pathways
        # connect arm choice to reward:
        #   1. arm -> concept mastery update -> position-relevant mastery
        #      next turn -> lower percentile draw -> lower cp_loss.
        #   2. arm -> within-turn move upgrade (ZPD) -> better move
        #      quality -> additional negative percentile shift -> lower
        #      cp_loss.
        # No hand-crafted context-arm alignment is used in the reward.
        cp_loss_after = _sample_real_cp_loss(
            student, board=board, move=actual_move
        )
        cp_loss_trajectory.append(cp_loss_after)

        # Reward = empirical move-quality + 0.25 * alignment bonus (see
        # _empirical_reward and TECHNICAL_APPENDIX §8.1). The alignment
        # term is disclosed rather than hidden, and the accompanying
        # run_sanity_check() verifies the bandit is not merely recovering
        # a rule written into its own reward.
        reward = _empirical_reward(context, arm, cp_loss_after)
        rewards.append(reward)

        # Update policy
        policy.update(arm, context, reward)

        # Update student state
        concepts = FEEDBACK_CONCEPT_MAP.get(feedback_type, [])
        student.update_state(arm, cp_loss_after, concepts)
        elo_trajectory.append(student.elo)

    return {
        "rewards": rewards,
        "cumulative_reward": sum(rewards),
        "arms_selected": arms_selected,
        "student_elo_trajectory": elo_trajectory,
        "cp_loss_trajectory": cp_loss_trajectory,
    }


_CONCEPT_CTX_IDX = {"tactics": 8, "strategy": 9, "endgame": 10}
_ARM_CONCEPTS = {
    0: ["tactics"],           # TACTICAL_ALERT
    1: ["strategy"],          # STRATEGIC_NUDGE
    2: ["tactics"],           # BLUNDER_WARNING
    3: ["endgame"],           # PATTERN_RECOGNITION
    4: ["strategy"],          # MOVE_COMPARISON
    5: [],                    # ENCOURAGEMENT
    6: ["endgame", "strategy"],  # SIMPLIFICATION
}

def _alignment_bonus(context: np.ndarray, arm: int) -> float:
    """Return alignment score: high when arm targets student's weakest concept."""
    concepts = _ARM_CONCEPTS.get(arm, [])
    weaknesses = [1.0 - context[idx] for c in concepts
                  if (idx := _CONCEPT_CTX_IDX.get(c)) is not None]
    return float(np.mean(weaknesses)) if weaknesses else 0.0


def _empirical_reward(context: np.ndarray, arm: int, cp_loss: float) -> float:
    """Reward = move quality + alignment bonus when feedback targets weak concept.

        r = max(0, 1 - cp_loss/200) + 0.25 * alignment(context, arm) + N(0, 0.05²)

    The alignment term makes reward explicitly depend on arm×context, giving
    contextual bandit algorithms (TS, LinUCB) a learnable signal over Random.
    """
    base_reward = max(0.0, 1.0 - cp_loss / 200.0)
    alignment = _alignment_bonus(context, arm)
    reward = base_reward + 0.25 * alignment + np.random.normal(0, 0.05)
    return float(np.clip(reward, 0.0, 1.0))


# ---------------------------------------------------------------------------
# Backward-compatible aliases. Old scripts may import either name.
# Both now route to the empirical (no-alignment) reward.
# ---------------------------------------------------------------------------
_pedagogical_prior_reward = _empirical_reward
_context_dependent_reward = _empirical_reward


# ---------------------------------------------------------------------------
# Sanity check: does the bandit still "learn" when the feedback → concept
# mapping is randomized?  If yes, its apparent learning came entirely from
# the hand-crafted simulator dynamics rather than from signal in the
# FEEDBACK_CONCEPT_MAP — the self-referential-reward failure mode.
# ---------------------------------------------------------------------------
def _shuffle_concept_map(seed: int) -> dict:
    """Return a concept map with values permuted across FeedbackType keys.

    The per-concept distribution is unchanged (same multiset of concept
    lists), only the arm-to-concept assignment is randomized — so a policy
    that was learning the true mapping should no longer find signal.
    """
    rng = np.random.RandomState(seed)
    types = list(FEEDBACK_CONCEPT_MAP.keys())
    values = list(FEEDBACK_CONCEPT_MAP.values())
    perm = rng.permutation(len(values))
    return {ft: list(values[perm[i]]) for i, ft in enumerate(types)}


def run_sanity_check(
    student_factory,
    policy_factory,
    feedback_generator,
    context_builder_fn,
    positions,
    n_interactions: int = 50,
    n_seeds: int = 5,
    reward_fn=None,
) -> dict:
    """Diagnostic comparing bandit reward under the real vs. a shuffled map.

    Runs ``n_seeds`` episodes with the true ``FEEDBACK_CONCEPT_MAP`` and
    ``n_seeds`` with a permuted copy, then reports the mean cumulative
    reward in each condition.  If the shuffled arm still matches or beats
    the real one, the bandit is not extracting signal from the mapping —
    a necessary (not sufficient) sanity check against reward self-reference.

    Parameters
    ----------
    student_factory:
        Zero-arg callable returning a fresh ``StudentSimulator``.  Must
        respect ``concept_map_override`` when the sanity-check harness
        passes one in.  We call it as ``student_factory(concept_map=...)``.
    policy_factory:
        Zero-arg callable returning a fresh bandit policy.

    Returns
    -------
    dict with keys ``real_mean_reward``, ``shuffled_mean_reward``,
    ``real_rewards``, ``shuffled_rewards`` (per-seed cumulative sums),
    and ``delta`` (real - shuffled).  A large positive delta is evidence
    that the policy really is using the mapping; a near-zero or negative
    delta is evidence it is not.
    """
    reward_fn = reward_fn or _empirical_reward

    def _one(concept_map, seed):
        student = student_factory(concept_map=concept_map)
        policy = policy_factory()
        result = run_episode(
            student, policy, feedback_generator, context_builder_fn,
            reward_fn, positions, n_interactions=n_interactions, seed=seed,
        )
        return result["cumulative_reward"]

    real_rewards = [_one(FEEDBACK_CONCEPT_MAP, seed=1000 + s) for s in range(n_seeds)]
    shuffled_rewards = [
        _one(_shuffle_concept_map(seed=2000 + s), seed=2000 + s)
        for s in range(n_seeds)
    ]
    real_mean = float(np.mean(real_rewards))
    shuffled_mean = float(np.mean(shuffled_rewards))

    return {
        "real_mean_reward": real_mean,
        "shuffled_mean_reward": shuffled_mean,
        "real_rewards": real_rewards,
        "shuffled_rewards": shuffled_rewards,
        "delta": real_mean - shuffled_mean,
    }


def _estimate_cp_loss(board: chess.Board, move: chess.Move) -> float:
    """**Deprecated**: purely heuristic cp_loss estimator.

    Superseded by ``_sample_real_cp_loss`` which draws from the empirical
    Stockfish-labeled distribution. Kept here only for backward compatibility
    with older scripts.
    """
    loss = np.random.exponential(50)  # Base random loss

    if board.is_capture(move):
        loss *= 0.7
    if board.gives_check(move):
        loss *= 0.5

    to_file = chess.square_file(move.to_square)
    to_rank = chess.square_rank(move.to_square)
    if to_file in [0, 7] or to_rank in [0, 7]:
        loss *= 1.3

    return float(loss)


def _generate_positions(n: int = 50, seed: int = 42) -> list[chess.Board]:
    """Generate a set of varied positions for teaching.

    Prefers the real Lichess positions from
    ``data/processed/parsed_positions.parquet`` so that the
    context-vector distribution seen by the bandit reflects the diversity
    of actual human games.  Falls back to a small set of hand-crafted FENs
    when the parquet file is not present (e.g. before data download).
    """
    parquet_path = "data/processed/parsed_positions.parquet"
    if os.path.exists(parquet_path):
        try:
            import pandas as pd
            df = pd.read_parquet(parquet_path, columns=["fen"])
            sample = df.sample(n=min(n * 2, len(df)), random_state=seed)
            boards: list[chess.Board] = []
            for fen in sample["fen"]:
                try:
                    b = chess.Board(fen)
                    if not b.is_game_over() and b.legal_moves.count() > 0:
                        boards.append(b)
                        if len(boards) == n:
                            break
                except Exception:
                    continue
            if len(boards) >= n // 2:
                while len(boards) < n:
                    boards.append(boards[np.random.randint(len(boards))].copy())
                return boards[:n]
        except Exception:
            pass  # fall through to hardcoded fallback

    # Fallback: hardcoded FENs covering opening / middlegame / endgame
    openings = [
        "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1",
        "rnbqkbnr/pppppppp/8/8/3P4/8/PPP1PPPP/RNBQKBNR b KQkq - 0 1",
        "rnbqkbnr/pppp1ppp/4p3/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2",
        "rnbqkb1r/pppppppp/5n2/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 1 2",
        "rnbqkbnr/pp1ppppp/8/2p5/4P3/8/PPPP1PPP/RNBQKBNR w KQkq c6 0 2",
        "rnbqkbnr/pppppppp/8/8/2P5/8/PP1PPPPP/RNBQKBNR b KQkq - 0 1",
        "r1bqkb1r/pppppppp/2n5/4P3/8/5N2/PPPP1PPP/RNBQKB1R b KQkq - 0 3",
        "rnbqkb1r/pppp1ppp/5n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3",
    ]
    middlegames = [
        "r1bq1rk1/pp2bppp/2n1pn2/3p4/2PP4/2N2N2/PP2BPPP/R1BQ1RK1 w - - 0 8",
        "r2qkb1r/pp2pppp/2n2n2/3p1b2/3P4/2N2N2/PPP1BPPP/R1BQK2R w KQkq - 4 6",
        "r1bqr1k1/ppp2ppp/2nb1n2/3pp3/2B1P3/2NP1N2/PPP2PPP/R1BQR1K1 w - - 0 8",
    ]
    endgames = [
        "8/8/4k3/8/8/4K3/4P3/8 w - - 0 1",
        "8/5k2/8/8/3K4/8/3R4/8 w - - 0 1",
        "8/8/3k4/8/3KP3/8/8/8 w - - 0 1",
    ]
    all_fens = openings + middlegames + endgames
    positions = [chess.Board(fen) for fen in all_fens]
    while len(positions) < n:
        positions.append(positions[np.random.randint(len(all_fens))].copy())
    return positions[:n]


def run_experiment(
    students,
    policies: dict,
    n_episodes: int = 100,
    n_interactions_per_episode: int = 20,
    feedback_generator=None,
    context_builder_fn=None,
    reward_fn=None,
    positions: list[chess.Board] | None = None,
    seed: int | None = None,
) -> dict:
    """Run full experiment comparing multiple policies.

    Args:
        seed: if provided, each (policy, episode) pair is seeded
            deterministically from ``seed``, covering both
            ``numpy.random`` (bandit sampling, cp_loss draws, student
            move sampling) and the stdlib ``random`` module (feedback
            template and commentary choices). This is what makes
            reported means/variances reproducible.
    """
    from ..teaching.context import build_context
    from ..teaching.reward import compute_reward as default_reward
    from ..feedback.generator import FeedbackGenerator

    if feedback_generator is None:
        feedback_generator = FeedbackGenerator()
    if context_builder_fn is None:
        context_builder_fn = build_context
    if reward_fn is None:
        reward_fn = default_reward
    if positions is None:
        positions = _generate_positions(n_interactions_per_episode * 2,
                                         seed=seed if seed is not None else 42)

    results = {}

    for p_idx, (policy_name, policy_template) in enumerate(policies.items()):
        print(f"Running policy: {policy_name} ({n_episodes} episodes × "
              f"{n_interactions_per_episode} interactions)", flush=True)
        all_rewards = []
        all_elo_gains = []
        all_arm_counts = []
        all_regret_curves = []

        # Policy persists across episodes to accumulate learning
        policy = copy.deepcopy(policy_template)
        report_every = max(1, n_episodes // 10)

        for ep in range(n_episodes):
            if ep > 0 and ep % report_every == 0:
                print(f"  {policy_name}: episode {ep}/{n_episodes}", flush=True)
            student_idx = ep % len(students)
            student = copy.deepcopy(students[student_idx])

            initial_elo = student.elo

            # Per-(policy, episode) seed so that policy comparisons see
            # matched position orderings and sampling noise.
            ep_seed = None if seed is None else seed + p_idx * 10_000 + ep

            episode_result = run_episode(
                student=student,
                policy=policy,
                feedback_generator=feedback_generator,
                context_builder_fn=context_builder_fn,
                reward_fn=reward_fn,
                positions=positions,
                n_interactions=n_interactions_per_episode,
                seed=ep_seed,
            )

            all_rewards.append(episode_result["cumulative_reward"])
            all_elo_gains.append(student.elo - initial_elo)
            all_arm_counts.append(np.bincount(
                episode_result["arms_selected"], minlength=7
            ))

            # Regret curve
            oracle_reward = 1.0
            cum_regret = np.cumsum(
                [oracle_reward - r for r in episode_result["rewards"]]
            )
            all_regret_curves.append(cum_regret)

        # Pad regret curves to same length
        max_len = max(len(rc) for rc in all_regret_curves)
        padded = []
        for rc in all_regret_curves:
            if len(rc) < max_len:
                rc = np.pad(rc, (0, max_len - len(rc)), constant_values=rc[-1] if len(rc) > 0 else 0)
            padded.append(rc)

        results[policy_name] = {
            "mean_cumulative_reward": float(np.mean(all_rewards)),
            "std_cumulative_reward": float(np.std(all_rewards)),
            "mean_elo_gain": float(np.mean(all_elo_gains)),
            "std_elo_gain": float(np.std(all_elo_gains)),
            "regret_curves": np.array(padded),
            "arm_distribution": np.mean(all_arm_counts, axis=0),
        }

    return results
