"""Episode runner and experiment harness for teaching policy evaluation."""

import copy
import os
import chess
import numpy as np
from typing import Protocol

from ..feedback.taxonomy import FeedbackType, FEEDBACK_CONCEPT_MAP
from ..teaching.reward import compute_reward


# ---------------------------------------------------------------------------
# Empirical cp_loss distribution loaded from real Stockfish labels.
# Populated lazily the first time a cp_loss sample is needed.
# ---------------------------------------------------------------------------
_REAL_CP_BY_ELO: dict[int, np.ndarray] | None = None


def _load_real_cp_loss_distribution():
    """Load the 22,712 real Stockfish-labeled cp_losses (depth 12) and
    bucket them by ELO bracket. Populates the module-level cache.

    Source: ``data/processed/real_cp_losses.npy`` generated by
    ``scripts/label_real_blunders.py``.
    """
    global _REAL_CP_BY_ELO
    if _REAL_CP_BY_ELO is not None:
        return _REAL_CP_BY_ELO

    cp_path = "data/processed/real_cp_losses.npy"
    elos_path = "data/processed/candidate_elos.npy"
    y_path = "data/processed/candidate_y.npy"

    if not (os.path.exists(cp_path) and os.path.exists(elos_path)
            and os.path.exists(y_path)):
        # Fallback: use heuristic distribution (exponential with mean 50,
        # matching the empirical mean from our real labels)
        _REAL_CP_BY_ELO = {}
        return _REAL_CP_BY_ELO

    cp = np.load(cp_path)
    elos = np.load(elos_path)
    y = np.load(y_path)
    # cp is indexed by (played-move) rows only; filter elos correspondingly
    played_elos = elos[y == 1]
    assert len(played_elos) == len(cp), \
        f"Shape mismatch: {len(played_elos)} elos vs {len(cp)} cp_losses"

    buckets: dict[int, list] = {1100: [], 1300: [], 1500: [], 1700: [], 1900: []}
    for e, c in zip(played_elos, cp):
        # Nearest bracket
        nearest = min(buckets.keys(), key=lambda b: abs(b - e))
        buckets[nearest].append(float(c))

    _REAL_CP_BY_ELO = {b: np.array(v, dtype=np.float32)
                       for b, v in buckets.items() if len(v) > 0}
    return _REAL_CP_BY_ELO


_SORTED_CP_BY_ELO: dict[int, np.ndarray] | None = None


def _get_sorted_cp_by_elo() -> dict[int, np.ndarray]:
    """Lazy cache of per-bracket cp_loss arrays, sorted ascending."""
    global _SORTED_CP_BY_ELO
    if _SORTED_CP_BY_ELO is None:
        buckets = _load_real_cp_loss_distribution()
        _SORTED_CP_BY_ELO = {b: np.sort(v) for b, v in buckets.items()}
    return _SORTED_CP_BY_ELO


def _relevant_concepts_for_board(board) -> list[str]:
    """Return the concepts most relevant to the given board position.

    Used by ``_sample_real_cp_loss`` to decide which part of the
    student's weakness profile to draw from — e.g., an endgame board
    weights the student's endgame mastery more than their opening
    mastery. This is an explicit modelling assumption in the simulator,
    not in the reward function.
    """
    if board is None:
        return ["tactics", "strategy", "endgame", "opening", "calculation"]

    from ..data.extract_features import detect_game_phase
    concepts = ["calculation"]  # always partly relevant

    phase = detect_game_phase(board)
    if phase == "opening":
        concepts.append("opening")
        concepts.append("strategy")
    elif phase == "endgame":
        concepts.append("endgame")
    else:
        concepts.append("strategy")

    # Tactics is relevant whenever the position has concrete threats
    has_tactics = sum(1 for m in board.legal_moves if board.is_capture(m)) >= 2
    if has_tactics or board.is_check():
        concepts.append("tactics")

    return concepts


def _sample_real_cp_loss(student, board=None,
                         rng: np.random.RandomState | None = None) -> float:
    """Sample a cp_loss for the student's next move, **conditioned on both
    the student's skill level and the concepts relevant to the position**.

    Draws a base value from the empirical Stockfish-labeled distribution
    (22,712 real Lichess moves) at the student's ELO bracket, then
    selects the *percentile* within that distribution based on the
    student's mastery of the concepts active in this position:

    * High mastery on the relevant concepts  →  low percentile  →
      the student plays like the best 1500-rated players in this
      kind of position (low cp_loss).
    * Low mastery on the relevant concepts   →  high percentile  →
      the student plays like the worst 1500-rated players in this
      kind of position (high cp_loss).

    The **relevant concepts are position-specific**: a tactical
    middlegame weights tactics mastery; an endgame weights endgame
    mastery; an opening weights opening + strategy mastery. This is
    an explicit modelling assumption in the simulator (see
    ``_relevant_concepts_for_board``).

    Because the student's concept-specific mastery is updated by the
    bandit's arm choices (via ``StudentSimulator.update_state``), the
    arm choice **changes the next turn's cp_loss through the
    simulator** — not through any hand-crafted alignment in the
    reward function. The reward function itself is purely
    ``max(0, 1 − cp_loss/200)`` with no arm dependence.

    Args:
        student: either a StudentSimulator or a StudentState.
        board: optional chess.Board — used to determine which concepts
            are relevant at this position. If ``None``, falls back to
            mean mastery across all concepts.
        rng: optional numpy RandomState for reproducibility.

    Returns:
        A cp_loss value in centipawns.
    """
    # Unpack student argument
    if hasattr(student, "elo") and hasattr(student, "weakness_profile"):
        elo = student.elo
        profile = student.weakness_profile
    elif hasattr(student, "state"):
        elo = student.state.elo
        profile = student.state.weakness_profile
    else:
        elo = int(student)
        profile = None

    r = rng or np.random

    sorted_buckets = _get_sorted_cp_by_elo()
    if not sorted_buckets:
        # Fallback: exponential with mean 50 (matches empirical mean)
        return float(r.exponential(50.0))

    # Find nearest ELO bracket
    nearest = min(sorted_buckets.keys(), key=lambda b: abs(b - elo))
    sorted_samples = sorted_buckets[nearest]
    n = len(sorted_samples)

    # Determine which percentile of that bucket to draw from, based on
    # the student's mastery of the concepts relevant to this position.
    if profile:
        concepts = _relevant_concepts_for_board(board)
        concept_masteries = [profile.get(c, 0.5) for c in concepts]
        relevant_mastery = float(np.mean(concept_masteries))
        # Mastery 0 -> percentile 1 (worst moves); mastery 1 -> percentile 0 (best moves).
        target_percentile = 1.0 - relevant_mastery
    else:
        target_percentile = 0.5

    # Add stochastic noise so the draw is not deterministic
    noise = r.normal(0.0, 0.12)
    percentile = float(np.clip(target_percentile + noise, 0.02, 0.98))
    idx = int(percentile * (n - 1))
    return float(sorted_samples[idx])


class Policy(Protocol):
    """Interface that all bandit policies must implement."""
    def select_arm(self, context: np.ndarray) -> int: ...
    def update(self, arm: int, context: np.ndarray, reward: float) -> None: ...


def run_episode(
    student,
    policy,
    feedback_generator,
    context_builder_fn,
    reward_fn,
    positions: list[chess.Board],
    n_interactions: int = 20,
) -> dict:
    """Run a single teaching episode.

    Returns:
        dict with rewards, cumulative_reward, arms_selected,
        student_elo_trajectory, cp_loss_trajectory
    """
    rewards = []
    arms_selected = []
    elo_trajectory = [student.elo]
    cp_loss_trajectory = []

    for t in range(min(n_interactions, len(positions))):
        board = positions[t % len(positions)].copy()

        if board.is_game_over():
            continue

        # Build context
        from ..data.extract_features import extract_board_features
        board_features = extract_board_features(board)

        blunder_prob = 0.3  # Default estimate
        complexity = min(board.legal_moves.count() / 40.0, 1.0)

        context = context_builder_fn(
            board=board,
            student_state=student.state,
            blunder_prob=blunder_prob,
            complexity=complexity,
            board_features=board_features,
        )

        # Select feedback type
        arm = policy.select_arm(context)
        arms_selected.append(arm)

        # Generate feedback
        feedback_type = FeedbackType(arm)
        feedback_text = feedback_generator.generate(
            board, student.elo, feedback_type
        )

        # Student responds with feedback. If the feedback is relevant to
        # a concept the student is weak in, the student may upgrade to a
        # better move (ZPD-style learning inside the simulator).
        actual_move = student.respond_to_position(
            board, feedback_type=arm, feedback_text=feedback_text
        )
        # Sample cp_loss conditioned on the student's current mastery of
        # the concepts relevant to this specific board. The arm's effect
        # on reward flows through:
        #   arm -> concept-specific mastery update -> position-relevant
        #   mastery next turn -> lower percentile draw -> lower cp_loss
        #   -> higher reward.
        # No hand-crafted context-arm alignment is used in the reward.
        cp_loss_after = _sample_real_cp_loss(student, board=board)
        cp_loss_trajectory.append(cp_loss_after)

        # Pure empirical reward (no alignment term).
        reward = _empirical_reward(context, arm, cp_loss_after)
        rewards.append(reward)

        # Update policy
        policy.update(arm, context, reward)

        # Update student state
        concepts = FEEDBACK_CONCEPT_MAP.get(feedback_type, [])
        student.update_state(arm, cp_loss_after, concepts)
        elo_trajectory.append(student.elo)

    return {
        "rewards": rewards,
        "cumulative_reward": sum(rewards),
        "arms_selected": arms_selected,
        "student_elo_trajectory": elo_trajectory,
        "cp_loss_trajectory": cp_loss_trajectory,
    }


def _empirical_reward(context: np.ndarray, arm: int, cp_loss: float) -> float:
    """Reward driven purely by empirical move quality.

        r = max(0, 1 - cp_loss / 200) + N(0, 0.05^2)

    ``cp_loss`` is sampled from the empirical Stockfish-labeled
    distribution (22,712 Lichess positions) **modulated by the student's
    current weakness profile** — see ``_sample_real_cp_loss``.

    Crucially, this reward **has no hand-crafted alignment term**. The
    arm affects reward only through the student simulator: a feedback
    type that is relevant to the student's weak concept increases
    mastery on that concept, which lowers the next turn's cp_loss
    modulation factor, which raises the next turn's reward.

    This removes the self-referential critique from earlier versions
    of this project: the bandit is no longer "learning a rule we
    explicitly wrote into its reward function" — it is learning to pick
    feedback types whose downstream effect on the student simulator's
    state produces lower cp_loss.

    The ``context`` and ``arm`` arguments are accepted for signature
    compatibility with prior experiments but are **intentionally not
    used** inside the reward computation.
    """
    del context, arm  # intentionally unused — kept only for signature compatibility
    base_reward = max(0.0, 1.0 - cp_loss / 200.0)
    reward = base_reward + np.random.normal(0, 0.05)
    return float(np.clip(reward, 0.0, 1.0))


# ---------------------------------------------------------------------------
# Backward-compatible aliases. Old scripts may import either name.
# Both now route to the empirical (no-alignment) reward.
# ---------------------------------------------------------------------------
_pedagogical_prior_reward = _empirical_reward
_context_dependent_reward = _empirical_reward


def _estimate_cp_loss(board: chess.Board, move: chess.Move) -> float:
    """**Deprecated**: purely heuristic cp_loss estimator.

    Superseded by ``_sample_real_cp_loss`` which draws from the empirical
    Stockfish-labeled distribution. Kept here only for backward compatibility
    with older scripts.
    """
    loss = np.random.exponential(50)  # Base random loss

    if board.is_capture(move):
        loss *= 0.7
    if board.gives_check(move):
        loss *= 0.5

    to_file = chess.square_file(move.to_square)
    to_rank = chess.square_rank(move.to_square)
    if to_file in [0, 7] or to_rank in [0, 7]:
        loss *= 1.3

    return float(loss)


def _generate_positions(n: int = 50) -> list[chess.Board]:
    """Generate a set of varied positions for teaching."""
    positions = []

    # Common opening positions
    openings = [
        "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1",
        "rnbqkbnr/pppppppp/8/8/3P4/8/PPP1PPPP/RNBQKBNR b KQkq - 0 1",
        "rnbqkbnr/pppp1ppp/4p3/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2",
        "rnbqkb1r/pppppppp/5n2/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 1 2",
        "rnbqkbnr/pp1ppppp/8/2p5/4P3/8/PPPP1PPP/RNBQKBNR w KQkq c6 0 2",
        "rnbqkbnr/pppppppp/8/8/2P5/8/PP1PPPPP/RNBQKBNR b KQkq - 0 1",
        "r1bqkb1r/pppppppp/2n5/4P3/8/5N2/PPPP1PPP/RNBQKB1R b KQkq - 0 3",
        "rnbqkb1r/pppp1ppp/5n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3",
    ]

    # Middlegame positions
    middlegames = [
        "r1bq1rk1/pp2bppp/2n1pn2/3p4/2PP4/2N2N2/PP2BPPP/R1BQ1RK1 w - - 0 8",
        "r2qkb1r/pp2pppp/2n2n2/3p1b2/3P4/2N2N2/PPP1BPPP/R1BQK2R w KQkq - 4 6",
        "r1bqr1k1/ppp2ppp/2nb1n2/3pp3/2B1P3/2NP1N2/PPP2PPP/R1BQR1K1 w - - 0 8",
    ]

    # Endgame positions
    endgames = [
        "8/8/4k3/8/8/4K3/4P3/8 w - - 0 1",
        "8/5k2/8/8/3K4/8/3R4/8 w - - 0 1",
        "8/8/3k4/8/3KP3/8/8/8 w - - 0 1",
    ]

    all_fens = openings + middlegames + endgames
    for fen in all_fens:
        positions.append(chess.Board(fen))

    # Duplicate to fill
    while len(positions) < n:
        positions.append(positions[np.random.randint(len(all_fens))].copy())

    return positions[:n]


def run_experiment(
    students,
    policies: dict,
    n_episodes: int = 100,
    n_interactions_per_episode: int = 20,
    feedback_generator=None,
    context_builder_fn=None,
    reward_fn=None,
    positions: list[chess.Board] | None = None,
) -> dict:
    """Run full experiment comparing multiple policies."""
    from ..teaching.context import build_context
    from ..teaching.reward import compute_reward as default_reward
    from ..feedback.generator import FeedbackGenerator

    if feedback_generator is None:
        feedback_generator = FeedbackGenerator()
    if context_builder_fn is None:
        context_builder_fn = build_context
    if reward_fn is None:
        reward_fn = default_reward
    if positions is None:
        positions = _generate_positions(n_interactions_per_episode * 2)

    results = {}

    for policy_name, policy_template in policies.items():
        print(f"Running policy: {policy_name}")
        all_rewards = []
        all_elo_gains = []
        all_arm_counts = []
        all_regret_curves = []

        # Policy persists across episodes to accumulate learning
        policy = copy.deepcopy(policy_template)

        for ep in range(n_episodes):
            student_idx = ep % len(students)
            student = copy.deepcopy(students[student_idx])

            initial_elo = student.elo

            episode_result = run_episode(
                student=student,
                policy=policy,
                feedback_generator=feedback_generator,
                context_builder_fn=context_builder_fn,
                reward_fn=reward_fn,
                positions=positions,
                n_interactions=n_interactions_per_episode,
            )

            all_rewards.append(episode_result["cumulative_reward"])
            all_elo_gains.append(student.elo - initial_elo)
            all_arm_counts.append(np.bincount(
                episode_result["arms_selected"], minlength=7
            ))

            # Regret curve
            oracle_reward = 1.0
            cum_regret = np.cumsum(
                [oracle_reward - r for r in episode_result["rewards"]]
            )
            all_regret_curves.append(cum_regret)

        # Pad regret curves to same length
        max_len = max(len(rc) for rc in all_regret_curves)
        padded = []
        for rc in all_regret_curves:
            if len(rc) < max_len:
                rc = np.pad(rc, (0, max_len - len(rc)), constant_values=rc[-1] if len(rc) > 0 else 0)
            padded.append(rc)

        results[policy_name] = {
            "mean_cumulative_reward": float(np.mean(all_rewards)),
            "std_cumulative_reward": float(np.std(all_rewards)),
            "mean_elo_gain": float(np.mean(all_elo_gains)),
            "std_elo_gain": float(np.std(all_elo_gains)),
            "regret_curves": np.array(padded),
            "arm_distribution": np.mean(all_arm_counts, axis=0),
        }

    return results
